openapi: 3.1.0
info:
  title: Fediverse Auxiliary Service Providers - General provider API
  description: |-
    This file describes the basic API every "Fediverse Auxiliary
    Service Provider" needs to provide.

    See
    [the full specification](https://github.com/mastodon/fediverse_auxiliary_service_provider_specifications/tree/main/general/v0.1)
    for all the details.
  version: '0.1'
externalDocs:
  description: Fediverse Auxiliary Service Provider Specifications
  url: https://github.com/mastodon/fediverse_auxiliary_service_provider_specifications
tags:
  - name: provider_info 
    description: Information about the provider 
    externalDocs:
      description: Find out more
      url: https://github.com/mastodon/fediverse_auxiliary_service_provider_specifications/tree/main/general/v0.1/provider_info.md 
paths:
  /provider_info:
    get:
      tags:
        - provider_info 
      summary: Provider information
      description: Necessary information an instance needs to know about the provider 
      operationId: showProviderInfo
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProviderInfo'
      security:
        - provider_auth: []
components:
  schemas:
    ProviderInfo:
      type: object
      properties:
        name:
          type: string
          examples: ["Example provider"]
        privacy_policy:
          type: array
          items:
            $ref: '#/components/schemas/PrivacyPolicy'
        capabilities:
          type: array
          items:
            $ref: '#/components/schemas/Capability'
        sign_in_url:
          type: string
          format: uri
          examples: ["https://provider.example.com/sign_in"]
    PrivacyPolicy:
      type: object
      properties:
        url:
          type: string
          format: url
          examples: ["https://provider.example.com/privacy_policy.html"]
        language:
          type: string
          examples: ["en", "en-GB", "de-CH"]
    Capability:
      type: object
      properties:
        id:
          type: string
          examples: ["trends", "account_search"]
        version:
          type: string
          examples: ["0.1", "1.0", "2.4"]
  securitySchemes:
    provider_auth:
      type: http
      scheme: signature
      description: "HTTP Message Signatures based authentication as described in https://github.com/mastodon/fediverse_auxiliary_service_provider_specifications/blob/main/general/v0.1/protocol_basics.md" 
