openapi: 3.1.0
info:
  title: Fediverse Auxiliary Service Providers - Debug Provider API
  description: |-
    This describes the API a "Debug Provider" needs to implement.

    See
    [the full specification](https://github.com/mastodon/fediverse_auxiliary_service_provider_specifications/tree/main/debug/v0.1)
    for all the details.
  version: '0.1'
externalDocs:
  description: Fediverse Auxiliary Service Provider Specifications
  url: https://github.com/mastodon/fediverse_auxiliary_service_provider_specifications
tags:
  - name: debug
    description: Make a debug request that gets logged and triggers a callback 
    externalDocs:
      description: Find out more
      url: https://github.com/mastodon/fediverse_auxiliary_service_provider_specifications/tree/main/debug/v0.1/debug_provider.md 
paths:
  /debug/log:
    post:
      tags:
        - debug
      summary: Debug call
      description: Make a debug request that gets logged and triggers a callback 
      operationId: createDebugLog
      requestBody:
        description: Optional payload that gets logged and appended to the callback  
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DebugPayload'
        required: false
      responses:
        '201':
          description: Successful operation
      security:
        - provider_auth: []
components:
  schemas:
    DebugPayload:
      type: object
  securitySchemes:
    provider_auth:
      type: http
      scheme: bearer
